db:
  host: "mudb.mulesoft-training.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  table: "flights_transactions"
  
filepath: "/Users/michaelcutler/Desktop/output/test"